CREATE TABLE `User` (
`ID` int NOT NULL AUTO_INCREMENT COMMENT '主键',
`USER_NAME` varchar(255) NOT NULL,
`USER_AGE` int NOT NULL DEFAULT 0 COMMENT '年龄',
`USER_GENDER` int(255) NOT NULL DEFAULT 1 COMMENT '性别',
PRIMARY KEY (`ID`) ,
INDEX `ID` (`ID`)
);

